---
name: MDBF deployment

on:
  push:
    paths:
      - .github/workflows/test_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  pull_request:
    paths:
      - .github/workflows/test_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  schedule:
    - cron: "10 5 * * 2"

jobs:
  molecule-mdbf-pkg:
    name: MDBF
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - debian-10
          - debian-11
          - debian-sid
          - fedora-36
          # - fedora-37
          - almalinux-8
          - almalinux-9
          - rockylinux-8
          - rockylinux-9
        mariadb-version:
          - "10.3"
          - "10.4"
          - "10.5"
          - "10.6"
          - "10.7"
          - "10.8"
          - "10.9"
          - "10.10"
        exclude:
          - distro: ubuntu-18.04
            mariadb-version: 10.3
          - distro: ubuntu-20.04
            mariadb-version: 10.3
          - distro: ubuntu-22.04
            mariadb-version: 10.3
          - distro: ubuntu-22.04
            mariadb-version: 10.4
          - distro: ubuntu-22.04
            mariadb-version: 10.5
          - distro: debian-10
            mariadb-version: 10.3
          - distro: debian-11
            mariadb-version: 10.3
          - distro: debian-11
            mariadb-version: 10.4
          - distro: debian-sid
            mariadb-version: 10.3
          - distro: debian-sid
            mariadb-version: 10.4
          - distro: fedora-36
            mariadb-version: 10.3
          - distro: fedora-36
            mariadb-version: 10.4
          - distro: fedora-36
            mariadb-version: 10.5
          - distro: almalinux-9
            mariadb-version: 10.3
          - distro: almalinux-9
            mariadb-version: 10.4
          - distro: rockylinux-9
            mariadb-version: 10.3
          - distro: rockylinux-9
            mariadb-version: 10.4

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
        # This is necessary on GH Actions to allow running systemd in rootless containers
        # see: https://github.com/actions/virtual-environments/issues/3536
        # see: https://github.com/ansible-community/molecule/discussions/3155
      - name: Start systemd user service
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      - name: Run molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: mdbf.yml
          MARIADB_VERSION: ${{ matrix.mariadb-version }}
