---
name: Cluster MDBF

on:
  push:
    paths:
      - .github/workflows/test_cluster_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/cluster/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  pull_request:
    paths:
      - .github/workflows/test_cluster_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/cluster/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  schedule:
    - cron: "30 5 * * 2"

jobs:
  molecule-cluster-pkg:
    name: Cluster MDBF
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-22.04
          - debian-11
          - fedora-36
          - almalinux-8
          - rockylinux-9
        mariadb-version:
          - "10.6"
          - "10.7"
          - "10.8"
          - "10.9"
          - "10.10"
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
        # This is necessary on GH Actions to allow running systemd in rootless containers
        # see: https://github.com/actions/virtual-environments/issues/3536
        # see: https://github.com/ansible-community/molecule/discussions/3155
      - name: Start systemd user service
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      - name: Run molecule
        run: molecule test -s cluster
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: mdbf.yml
          MARIADB_VERSION: ${{ matrix.mariadb-version }}
